name: Tests
on:
  push:
    branches:
    - dev
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: ./
        with:
          api_id: 1124980
          api_hash: '14sdg453sd6er656sery46ser4y'
          session: '69='
          redis_uri: 'jnl'
          redis_passwor: ${{ secrets.redis_password }}
        env:
          redis_password: ${{ secrets.redis_password }}
      - name: Direct Run
        run: |
              echo ${{ secrets.redis_password }}
