name: Tests
on:
  push:
    branches:
    - dev
  workflow_dispatch:


env:
  api_id: 1124980
  api_hash: '14sdg453sd6er656sery46ser4y'
  session: '69='
  redis_uri: 'jnl'
  redis_password: ${{ secrets.redis_password }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run
        uses: ./
